### ISSUE TITLE
Clock example error - Hardware v2

### ISSUE THREAD

**Issue by ayouboss** [Makerfabs/ESP32-S3-Parallel-TFT-with-Touch-4.3inch#4]
Compilation error: no matching function for call to 'Arduino_ESP32RGBPanel::Arduino_ESP32RGBPanel(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int)'

**Comment by zingo** [comment]
It could be that you picked up a the wrong version GFX Library for Arduino when I set up my project I had to lock it to 1.3.1
see:
https://github.com/zingo/CrazyCapyTime/blob/main/platformio.ini

I think the reason was some API change that I didn't want to bother fingering out. This was a few month back and on Hardware 1.3 so I might be the other way around now that you need later then 1.3.1

**Comment by ayouboss** [comment]
Thanks I will try that. I'm wondering if the same issue happens for LovyanGFX example: https://github.com/Makerfabs/ESP32-S3-Parallel-TFT-with-Touch-4.3inch/tree/main/examples/LovyanGFX_demo

When I upload the sketch I once get a full white screen, once full red, green, and blue screens. I've checked the Pinout in the header file and it seems to be correct. Comments even mention hardware v2.0.

Thanks in advance.

**Comment by vibr77** [comment]
Same here none of the exemple are working....
black screen for clock, random for LovyanGFX...

**Comment by seijikun** [comment]
I was able to get the clock example to build with `Arduino GFX 1.4.5` by replacing the [init code](https://github.com/Makerfabs/ESP32-S3-Parallel-TFT-with-Touch-4.3inch/blob/main/examples/Clock/Clock.ino#L10) with this:

```c++
Arduino_ESP32RGBPanel *bus = new Arduino_ESP32RGBPanel(
    40 /* DE */, 41 /* VSYNC */, 39 /* HSYNC */, 42 /* PCLK */,
    45 /* R0 */, 48 /* R1 */, 47 /* R2 */, 21 /* R3 */, 14 /* R4 */,
    5 /* G0 */, 6 /* G1 */, 7 /* G2 */, 15 /* G3 */, 16 /* G4 */, 4 /* G5 */,
    8 /* B0 */, 3 /* B1 */, 46 /* B2 */, 9 /* B3 */, 1 /* B4 */,
    0 /* hsync_polarity */, 8 /* hsync_front_porch */, 4 /* hsync_pulse_width */, 8 /* hsync_back_porch */,
    0 /* vsync_polarity */, 8 /* vsync_front_porch */, 4 /* vsync_pulse_width */, 8 /* vsync_back_porch */,
    1 /* pclk_active_neg */, 16000000 /* prefer_speed */, false, 0, 0
);
Arduino_RGB_Display* gfx = new Arduino_RGB_Display(800, 480, bus, 0, true, nullptr, GFX_NOT_DEFINED, nullptr, GFX_NOT_DEFINED, 0, 0, 0, 0);
```

**Comment by sukesh-ak** [comment]
Here is a simple example for the device using `LovyanGFX` to get you started.
https://gist.github.com/sukesh-ak/c8325c4bb7ec3da40f24977526d513f8
