### ISSUE TITLE
Arduino IDE 2.0.x

### ISSUE THREAD

**Issue by WanaGo** [Makerfabs/ESP32-S3-Parallel-TFT-with-Touch-4.3inch#1]
Hi,
Have you attempted to get the LVGL Benchmark to compile and build using the Arduino 2.0.x IDE, rather than the 1.8.x IDE?

I cant get it to compile, just get weird errors which dont really say much.

```
Using library lvgl at version 8.3.2 in folder: C:\Users\wanago\Documents\Arduino\libraries\mf_Lvgl 
Using library GFX Library for Arduino at version 1.3.2 in folder: C:\Users\wanago\Documents\Arduino\libraries\GFX_Library_for_Arduino 
Using library SPI at version 2.0.0 in folder: C:\Users\wanago\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\libraries\SPI 
Using library Wire at version 2.0.0 in folder: C:\Users\wanago\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\libraries\Wire
```

```
c:/users/wanago/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\wanago\AppData\Local\Temp\arduino\sketches\94789ED864D1E8CA07644E860EFAA592\sketch\objs.a(LvglBenchmark.ino.cpp.o):(.literal._Z5setupv+0x48): undefined reference to `lv_demo_benchmark'
c:/users/wanago/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\wanago\AppData\Local\Temp\arduino\sketches\94789ED864D1E8CA07644E860EFAA592\sketch\objs.a(LvglBenchmark.ino.cpp.o): in function `setup()':
C:\Users\wanago\AppData\Local\Temp\.arduinoIDE-unsaved2023214-6888-1djzjol.71qj\LvglBenchmark/LvglBenchmark.ino:168: undefined reference to `lv_demo_benchmark'
collect2.exe: error: ld returned 1 exit status exit status 1 Compilation error: exit status 1
```

I see there is LVGL 8.3.5 available now, but given this uses a modified version of that 8.3.2 library I cannot upgrade to that to try it.

Any suggestions?
